import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

class LegalScreen extends StatelessWidget {
  const LegalScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy & Terms'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: Theme.of(context).colorScheme.surface,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Theme.of(context).colorScheme.primary.withOpacity(0.15)),
          ),
          child: const MarkdownBody(
            data: _legalText,
            styleSheetTheme: MarkdownStyleSheetBaseTheme.material,
          ),
        ),
      ),
    );
  }
}

const String _legalText = '''
# Privacy Policy
**Last Updated: May 2026**

Welcome to Namma-Appeal. We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains how we collect, use, and share your information when you use our mobile application.

### 1. Information We Collect
We collect personal information that you voluntarily provide to us when you register on the app or draft Right to Information (RTI) applications.
* **Profile Data:** Full name, mobile number, physical address, and state.
* **Grievance Data:** Text descriptions of your grievances and images/scans of government documents or local issues you upload.
* **App Usage Data:** App preferences, history of generated drafts, and reminder schedules.

### 2. How We Use Your Information
We use your information strictly to provide and improve the Namma-Appeal service:
* To automatically fill in your Appellant details on RTI applications.
* To process text and images using Artificial Intelligence (Google Gemini) to generate accurate legal drafts.
* To schedule local notifications for RTI follow-up deadlines.
* To manage your account and authenticate you via Supabase.

### 3. Sharing Your Information
We do not sell your personal data. We only share information with the following third-party service providers necessary to operate the app:
* **Supabase:** To securely store your user profile, authentication tokens, and history of generated drafts.
* **Google Gemini API:** To analyze your scanned rejection letters and grievance descriptions. *Note: Data sent to AI models is strictly for generating your specific document and is subject to Google's API data privacy terms.*

### 4. Device Permissions
To function properly, Namma-Appeal requests the following permissions:
* **Camera/Photos:** To scan RTI rejection letters or capture photos of grievances.
* **Microphone:** To use speech-to-text features for describing your grievance.
* **Notifications & Alarms:** To alert you on Day 27 and Day 57 of your RTI filing cycle.

### 5. Your Rights
You have the right to access, update, or delete your information at any time. You can view and edit your profile within the app.

---

# Terms of Service
**Last Updated: May 2026**

By downloading, accessing, or using Namma-Appeal, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.

### 1. Service Description
Namma-Appeal is an AI-powered drafting tool designed to assist Indian citizens in formatting Right to Information (RTI) applications and First Appeals. **Namma-Appeal is not a law firm, and the use of this app does not constitute legal advice.**

### 2. User Responsibilities
* **Accuracy of Information:** You are solely responsible for verifying the accuracy of the RTI drafts generated by the AI before printing, signing, and submitting them to government authorities.
* **Lawful Use:** You agree to use the app only for lawful purposes. You must not use the app to generate defamatory, false, or malicious applications.
* **Account Security:** You are responsible for maintaining the confidentiality of your login credentials.

### 3. Disclaimer of Warranties
The app and all generated drafts are provided on an "AS IS" and "AS AVAILABLE" basis. While we strive to use advanced AI to generate accurate formatting, we make no guarantees regarding the legal success, accuracy, or acceptance of any RTI application or appeal generated through this app by any Public Information Officer (PIO).

### 4. Limitation of Liability
To the maximum extent permitted by law, Namma-Appeal and its developers shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the app. This includes, but is not limited to, missed legal deadlines, rejected applications, or loss of data. 

### 5. AI Generation Acknowledgment
You acknowledge that the legal drafts are generated by Artificial Intelligence. The AI may occasionally produce inaccurate, incomplete, or repetitive text (hallucinations). It is your mandatory responsibility to read and verify all outputs before relying on them.

### 6. Modifications to the App
We reserve the right to modify, suspend, or discontinue any feature of the app, including API access and PDF generation capabilities, at any time without prior notice.
''';